### ISSUE TITLE
Render Problem

### ISSUE THREAD

**Issue by drupesh2008** [florent37/DiagonalLayout#22]
I'm getting the following error!
because of which I'm not able to see the preview in Android Studio, but the output can be seen when run on an Android device.

**_**java.lang.IllegalArgumentException: Underflow in restoreToCount - more restores than saves
	at android.graphics.Canvas.restoreToCount(Canvas.java:599)
	at com.github.florent37.diagonallayout.DiagonalLayout.dispatchDraw(DiagonalLayout.java:295)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:550)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:760)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)**_**

**Comment by QuentR** [comment]
Exact same problem. Any solution ?

**Comment by florent37** [comment]
try with the 1.0.9

compile 'com.github.florent37:diagonallayout:1.0.9'
